### ISSUE TITLE
Rail climbing energy orbs not collecting

### ISSUE THREAD

**Issue by psummerfield** [CardboardKeep/Warden#30] opened 2015-02-13 10:46 UTC
![image](https://cloud.githubusercontent.com/assets/10220012/6186121/b89443de-b3c9-11e4-8695-7d462eda0d01.png)
The green balls of energy were not able to picked up while climbing across rail.

**Comment by Talsidor** [comment] 2015-02-16 00:50
Closing as this is a duplicate of #9

**Closed by Talsidor** 2015-02-16 00:50 UTC
