### ISSUE TITLE
Graphics: Enemy health bars are invisible when in front of a waterfall.

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#49] opened 2015-05-30 04:18 UTC
Repro: Find a level with an enemy and a waterfall. Move the camera so they overlap, the health bar will not draw where the waterfall is.

**Comment by jimbobrlw** [comment] 2015-06-05 02:14
unable to reproduce this issue, tried in the sewer canals and in my own test level. ill close the issue for now. might reopen in the future.

**Closed** 2015-06-05 02:23 UTC
Labels: bug
