### ISSUE TITLE
force crawl not working / head going through tunnel roof

### ISSUE THREAD

**Issue by psummerfield** [CardboardKeep/Warden#27] opened 2015-02-13 10:30 UTC
![image](https://cloud.githubusercontent.com/assets/10220012/6185879/6aa36512-b3c7-11e4-97bb-91f90c79217b.png)
Perhaps make the doorway higher?
;D

**Comment by Talsidor** [comment] 2015-02-16 00:53
@psummerfield Can you confirm which level this is?

**Comment by psummerfield** [comment] 2015-02-16 01:02
Yeh sure sorry. First level. secret flower battle inside tree entrence.

**Comment by psummerfield** [comment] 2015-02-16 01:04
I'll check before posting bug reports and minimize the duplicates.

**Comment by Talsidor** [comment] 2015-02-16 01:30
@psummerfield I just tried for 15 minutes and can't reproduce this in the same location. Would love a video if you can.

**Comment by psummerfield** [comment] 2015-02-16 11:14
i also tried and couldnt replicate it. I did play with trying to get a weapon in de-bug menu, so i am sorry, i might have bugged it accidently. ill play with only getting lanterns to find bugs.

**Comment by Talsidor** [comment] 2015-02-20 09:41
Closing this now as no reproducibles, feel free to open a new issue if repro is found.

**Closed by Talsidor** 2015-02-20 09:41 UTC

**Comment by psummerfield** [comment] 2015-02-20 09:43
no probs, I coudnt replicate it again either. ;)
