### ISSUE TITLE
Back button in options doesn't show up.

### ISSUE THREAD

**Issue by RabbitBrains** [CardboardKeep/Warden#107] opened 2015-10-21 04:09 UTC

**Comment by Agilethief** [comment] 2015-10-21 05:04
There is no description of this. 
@RabbitBrains In the future a screenshot showing this would be good.
Also make sure you can reproduce the bug.

**Comment by Talsidor** [comment] 2015-11-24 10:46
As mentioned in person last week this is most likely caused by the GUI zoom script (forget exact name) that is on virtually every selectable element. It uses coroutines to grow interactables approx. 10% when they're selected, shrinking back to normal when de-selected. I suspect they're shrinking some objects to 0%, especially since I've sometimes witnessed the buttons quickly racing away into non-existence.

**Comment by jimbobrlw** [comment] 2015-12-01 06:06
tried to fix this one, cant seem to get it to happen no matter what i try. will just have to close it until a repro is found or someone can show it to me or cal while its happening.

**Closed by jimbobrlw** 2015-12-01 06:06 UTC
Labels: bug, system: gui
