### ISSUE TITLE
3rd training level mini-bos issue

### ISSUE THREAD

**Issue by psummerfield** [CardboardKeep/Warden#32] opened 2015-02-16 10:44 UTC
hey guys, i think i mentioned this before and it got closed. But Ive been thinking about it and i guess i miss what you used to be able to do a few builds ago. Its a small thing, but it gives the player confidence that they can roll and duck!

The 3rd stone mini-boss with the heli-copter arms. In a previous built it was possible to wait till its arms stopped and roll underneath and crouch close the stone boss and then pop-up and whack it and then crouch or roll out and again unharmed.

A lass, this isnt possible any more, they player will always be hit by swinging arms weather its ducking or rolling and cant crouch-hide in the sweet spot.

anyway, just a thought id let ya know. ;P again....
o

**Comment by Agilethief** [comment] 2015-02-17 07:48
Hey Paul,

I miss that too, but unless I am working in that area I won't get the time
to look at it right now. What should happen is once we've finished filling
the rest of the game with content we will come back through and polish
everything up.


On Mon, Feb 16, 2015 at 9:44 PM, psummerfield <notifications@github.com>
wrote:

> hey guys, i think i mentioned this before and it got closed. But Ive been
> thinking about it and i guess i miss what you used to be able to do a few
> builds ago. Its a small thing, but it gives the player confidence that they
> can roll and duck!
>
> The 3rd stone mini-boss with the heli-copter arms. In a previous built it
> was possible to wait till its arms stopped and roll underneath and crouch
> close the stone boss and then pop-up and whack it and then crouch or roll
> out and again unharmed.
>
> A lass, this isnt possible any more, they player will always be hit by
> swinging arms weather its ducking or rolling and cant crouch-hide in the
> sweet spot.
>
> anyway, just a thought id let ya know. ;P again....
> o
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CardboardKeep/Warden/issues/32>.
>



-- 
Timothy Bermanseder
Co-Founder of Cardboard Keep.
Lead Artist.

CardboardKeep.com/ <http://cardboardkeep.com/>

Twitter.com/AgileTim <https://twitter.com/AgileTim>
au.Linkedin.com/in/TimothyBermanseder
<http://au.linkedin.com/in/timothybermanseder>

**Comment by psummerfield** [comment] 2015-02-18 05:45
Hey tim

Yeah i understand. New build is really epic. Would you like anyone else to
play test? I know an 10 year old is super keen to play the game!
:)
P

**Comment by Talsidor** [comment] 2015-02-20 09:40
Hey Paul,
Not right now as we're leaving testing until everything is in. Right now we know enough about what isn't working, so getting more info on that now wouldn't be anywhere near as useful as when we're in 100% tweak and fix mode. Don't worry, it's getting close now =)

**Comment by Talsidor** [comment] 2015-10-06 02:54
Closing this as it's a suggestion not a bug, and the sequence has significantly changed since it was brought up.

**Closed by Talsidor** 2015-10-06 02:54 UTC
Labels: question, Sewer - Training Chamber
