### ISSUE TITLE
Invert Camera option not working

### ISSUE THREAD

**Issue by justgimmeafknname** [CardboardKeep/Warden#113] opened 2015-11-09 01:00 UTC
When doing anything, the invert camera option doesnt work

repro
go to any level
press I
this will not invert the camera

or

go to any level
open the settings menu
tick the "invert camera" box
this will not invert the camera

**Comment by jimbobrlw** [comment] 2015-11-17 06:31
FIXED! re-added this to the camrig script.

**Comment by jimbobrlw** [comment] 2015-11-17 06:58
REOPENED!

so the fix i put in is actually more of a workaround.
The real fix will be to figure out why the inverted camera toggle box in the menu isn't working.

**Comment by jimbobrlw** [comment] 2015-11-17 07:02
from what i can tell, clicking the toggle button in the menu only toggles the "Is On" variable, which is intended to dictate weather or not the button starts toggled or not.
currently the toggle only returns false, which is the default state, if you manually change the bool in the on value changed section of the toggle component, it returns true.

**Comment by Talsidor** [comment] 2015-11-24 10:34
To elaborate on what James said, the "I" key invert was just a workaround before we had menu settings. Now that these are in that should be used instead, and it should be saved as a PlayerPref and stay persistently how you set it on your PC. That said the settings option not working is definitely a bug.

**Comment by Talsidor** [comment] 2016-03-16 03:21
Confirmed fixed in 0.9.161

**Closed by Talsidor** 2016-03-16 03:21 UTC
Labels: bug, system: gui
