### ISSUE TITLE
Frozen player after shapeshifting and targeting?

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#115] opened 2015-11-19 03:33 UTC
NullReferenceException: Object reference not set to an instance of an object
Player.GhostTargeting () (at Assets/-Warden/Scripts/Entities/Wardens/Player.cs:460)
Player.Update () (at Assets/-Warden/Scripts/Entities/Wardens/Player.cs:255)

Repro:
Be Bitt
Be near a Bitt Pot and a Sling ring.
Have the target reticle over the Bitt Pott.
Shift into Tavian
Reticle jumps to sling ring.

Error is thrown, cannot move.
May be difficult to repro but had happen multiple times.

**Comment by Talsidor** [comment] 2015-11-24 08:51
Duplicate of #116

**Closed by Talsidor** 2015-11-24 08:51 UTC
Labels: bug
