### ISSUE TITLE
charecter floating above ground

### ISSUE THREAD

**Issue by psummerfield** [CardboardKeep/Warden#29] opened 2015-02-13 10:38 UTC
I noticed that the main characters feet were off the ground.
wasnt  obvious straight away

![image](https://cloud.githubusercontent.com/assets/10220012/6186026/9756b69e-b3c8-11e4-8834-5e811d153390.png)

**Comment by Talsidor** [comment] 2015-02-16 00:49
Closing as this is a duplicate of #2

**Closed by Talsidor** 2015-02-16 00:49 UTC
